<?php

namespace App\AppBundle\Repository;

/**
 * VendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendaRepository extends \Doctrine\ORM\EntityRepository
{
}
